sudo: false 

cache: pip

language: python

notifications:
  email: false

python:
    - 2.7
    - 3.6

script:
    - pip install -r ./requirements.txt
    - pip install python-coveralls mxnet
    - sh build.sh
    - nosetests --with-coverage

after_success:
    - coveralls
